[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/api/*"
to = "http://ec2-13-209-7-237.ap-northeast-2.compute.amazonaws.com:8080/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200